import { Profile, UserRole } from '../types';

export function getMockProfiles(): Profile[] {
  return [
    {
      id: '1',
      userId: '101',
      name: 'Cairo Design Studios',
      type: 'designer',
      specialty: 'Modern Furniture Design',
      description: 'Award-winning design studio specializing in contemporary furniture for residential and commercial spaces.',
      location: 'Cairo',
      experience: 12,
      website: 'https://example.com/cairodesign',
      phone: '+20 10 1234 5678',
      email: 'info@cairodesign.com',
      socialLinks: {
        facebook: 'https://facebook.com/cairodesign',
        instagram: 'https://instagram.com/cairodesign',
        linkedin: 'https://linkedin.com/company/cairodesign',
      },
      images: [
        'https://images.pexels.com/photos/3932930/pexels-photo-3932930.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
      ],
      featured: true,
      createdAt: '2022-01-15T12:00:00Z',
      updatedAt: '2023-05-10T14:30:00Z',
    },
    {
      id: '2',
      userId: '102',
      name: 'Alexandria Wood Suppliers',
      type: 'supplier',
      specialty: 'Premium Wood Materials',
      description: 'Leading supplier of high-quality wood for furniture manufacturing, specializing in imported and local wood varieties.',
      location: 'Alexandria',
      experience: 25,
      website: 'https://example.com/alexwood',
      phone: '+20 10 9876 5432',
      email: 'sales@alexwood.com',
      socialLinks: {
        facebook: 'https://facebook.com/alexwood',
        instagram: 'https://instagram.com/alexwood',
      },
      images: [
        'https://images.pexels.com/photos/3965520/pexels-photo-3965520.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
      ],
      featured: true,
      createdAt: '2021-03-22T10:15:00Z',
      updatedAt: '2023-04-18T09:45:00Z',
    },
    {
      id: '3',
      userId: '103',
      name: 'Delta Furniture Manufacturing',
      type: 'producer',
      specialty: 'Mass Production Furniture',
      description: 'Large-scale furniture manufacturer with state-of-the-art facilities for high-quality mass production.',
      location: 'Damietta',
      experience: 30,
      website: 'https://example.com/deltafurniture',
      phone: '+20 10 5555 7777',
      email: 'info@deltafurniture.com',
      socialLinks: {
        facebook: 'https://facebook.com/deltafurniture',
        instagram: 'https://instagram.com/deltafurniture',
        linkedin: 'https://linkedin.com/company/deltafurniture',
      },
      images: [
        'https://images.pexels.com/photos/5824877/pexels-photo-5824877.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
      ],
      featured: true,
      createdAt: '2020-05-10T08:30:00Z',
      updatedAt: '2023-03-15T11:20:00Z',
    },
    {
      id: '4',
      userId: '104',
      name: 'Luxor Home Collection',
      type: 'retailer',
      specialty: 'Premium Home Furniture',
      description: 'Upscale furniture retailer offering curated collections of high-end home furnishings and decor.',
      location: 'Giza',
      experience: 15,
      website: 'https://example.com/luxorhome',
      phone: '+20 10 2222 3333',
      email: 'sales@luxorhome.com',
      socialLinks: {
        facebook: 'https://facebook.com/luxorhome',
        instagram: 'https://instagram.com/luxorhome',
      },
      images: [
        'https://images.pexels.com/photos/1571460/pexels-photo-1571460.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
      ],
      featured: true,
      createdAt: '2021-09-01T14:45:00Z',
      updatedAt: '2023-02-28T16:10:00Z',
    },
    {
      id: '5',
      userId: '105',
      name: 'Cairo University Design Department',
      type: 'educational',
      specialty: 'Furniture Design Education',
      description: 'Academic department focused on furniture design, offering undergraduate and graduate programs.',
      location: 'Cairo',
      experience: 50,
      website: 'https://example.com/cairouniversity',
      phone: '+20 10 1111 9999',
      email: 'design@cairouniversity.edu',
      socialLinks: {
        facebook: 'https://facebook.com/cairouniversity',
        linkedin: 'https://linkedin.com/school/cairouniversity',
      },
      images: [
        'https://images.pexels.com/photos/256455/pexels-photo-256455.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
      ],
      featured: false,
      createdAt: '2020-01-15T09:00:00Z',
      updatedAt: '2023-01-10T10:30:00Z',
    },
    {
      id: '6',
      userId: '106',
      name: 'Ahmed Hassan',
      type: 'designer',
      specialty: 'Classical Egyptian Furniture Design',
      description: 'Independent designer specializing in furniture that blends classical Egyptian motifs with contemporary functionality.',
      location: 'Cairo',
      experience: 8,
      website: 'https://example.com/ahmedhassan',
      phone: '+20 10 8765 4321',
      email: 'ahmed@designstudio.com',
      socialLinks: {
        instagram: 'https://instagram.com/ahmedhassan',
        linkedin: 'https://linkedin.com/in/ahmedhassan',
      },
      images: [
        'https://images.pexels.com/photos/6489663/pexels-photo-6489663.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
      ],
      featured: false,
      createdAt: '2022-04-18T11:20:00Z',
      updatedAt: '2023-06-22T13:45:00Z',
    },
    {
      id: '7',
      userId: '107',
      name: 'Ministry of Trade and Industry',
      type: 'government',
      specialty: 'Furniture Export Promotion',
      description: 'Government entity responsible for promoting Egyptian furniture exports and supporting industry development.',
      location: 'Cairo',
      experience: 40,
      website: 'https://example.com/ministry',
      phone: '+20 10 4444 4444',
      email: 'furniture@ministry.gov.eg',
      socialLinks: {
        facebook: 'https://facebook.com/ministry',
        twitter: 'https://twitter.com/ministry',
      },
      images: [
        'https://images.pexels.com/photos/164338/pexels-photo-164338.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
      ],
      featured: false,
      createdAt: '2019-11-10T08:00:00Z',
      updatedAt: '2022-12-05T09:15:00Z',
    },
    {
      id: '8',
      userId: '108',
      name: 'Sara Ibrahim',
      type: 'student',
      specialty: 'Sustainable Furniture Design',
      description: 'Design student focusing on sustainable materials and eco-friendly furniture production methods.',
      location: 'Alexandria',
      experience: 2,
      website: 'https://example.com/saraibrahim',
      phone: '+20 10 9876 1234',
      email: 'sara.ibrahim@student.edu',
      socialLinks: {
        instagram: 'https://instagram.com/saraibrahim',
      },
      images: [
        'https://images.pexels.com/photos/6207368/pexels-photo-6207368.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
      ],
      featured: false,
      createdAt: '2022-09-05T15:30:00Z',
      updatedAt: '2023-07-12T14:20:00Z',
    },
    {
      id: '9',
      userId: '109',
      name: 'Damietta Furniture City',
      type: 'development',
      specialty: 'Furniture Industry Development',
      description: 'Major development project aiming to establish Damietta as a global furniture manufacturing and export hub.',
      location: 'Damietta',
      experience: 5,
      website: 'https://example.com/damiettafurniturecity',
      phone: '+20 10 7777 8888',
      email: 'info@damiettafurniturecity.com',
      socialLinks: {
        facebook: 'https://facebook.com/damiettafurniturecity',
        linkedin: 'https://linkedin.com/company/damiettafurniturecity',
      },
      images: [
        'https://images.pexels.com/photos/1094794/pexels-photo-1094794.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
      ],
      featured: false,
      createdAt: '2021-02-20T10:00:00Z',
      updatedAt: '2023-05-30T11:10:00Z',
    },
    {
      id: '10',
      userId: '110',
      name: 'Red Sea Metals',
      type: 'supplier',
      specialty: 'Metal Components for Furniture',
      description: 'Supplier of high-quality metal components, frames, and fittings for furniture manufacturing.',
      location: 'Suez',
      experience: 18,
      website: 'https://example.com/redseametals',
      phone: '+20 10 3333 6666',
      email: 'sales@redseametals.com',
      socialLinks: {
        facebook: 'https://facebook.com/redseametals',
        linkedin: 'https://linkedin.com/company/redseametals',
      },
      images: [
        'https://images.pexels.com/photos/670028/pexels-photo-670028.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
      ],
      featured: false,
      createdAt: '2020-08-15T13:20:00Z',
      updatedAt: '2023-04-05T16:45:00Z',
    },
    {
      id: '11',
      userId: '111',
      name: 'Modern Home Furnishings',
      type: 'retailer',
      specialty: 'Contemporary Furniture',
      description: 'Retail chain specializing in affordable contemporary furniture for urban homes and apartments.',
      location: 'Cairo',
      experience: 10,
      website: 'https://example.com/modernhome',
      phone: '+20 10 5555 1111',
      email: 'info@modernhome.com',
      socialLinks: {
        facebook: 'https://facebook.com/modernhome',
        instagram: 'https://instagram.com/modernhome',
      },
      images: [
        'https://images.pexels.com/photos/1813502/pexels-photo-1813502.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
      ],
      featured: false,
      createdAt: '2021-07-10T11:15:00Z',
      updatedAt: '2023-03-28T10:30:00Z',
    },
    {
      id: '12',
      userId: '112',
      name: 'Sinai Handicrafts',
      type: 'producer',
      specialty: 'Traditional Handcrafted Furniture',
      description: 'Artisanal producer of traditional handcrafted furniture using time-honored Egyptian techniques.',
      location: 'South Sinai',
      experience: 35,
      website: 'https://example.com/sinaihandicrafts',
      phone: '+20 10 2222 8888',
      email: 'info@sinaihandicrafts.com',
      socialLinks: {
        facebook: 'https://facebook.com/sinaihandicrafts',
        instagram: 'https://instagram.com/sinaihandicrafts',
      },
      images: [
        'https://images.pexels.com/photos/2079438/pexels-photo-2079438.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
      ],
      featured: false,
      createdAt: '2019-12-05T09:45:00Z',
      updatedAt: '2022-11-20T12:15:00Z',
    },
  ];
}